// Model Pokemon — menyimpan semua data tiap Pokemon
class Pokemon {
  final String nama;
  final String tipe;        // tipe utama
  final String gambar;      // nama file di assets/images/
  final String deskripsi;
  final String kemampuan;   // ability utama
  final String evolusi;     // info evolusi
  final List<String> kelemahan; // tipe yang menjadi kelemahan
  final int hp;
  final int attack;
  final int defense;
  final int speed;

  const Pokemon({
    required this.nama,
    required this.tipe,
    required this.gambar,
    required this.deskripsi,
    required this.kemampuan,
    required this.evolusi,
    required this.kelemahan,
    required this.hp,
    required this.attack,
    required this.defense,
    required this.speed,
  });
}

// Daftar Pokemon
final List<Pokemon> daftarPokemon = [
  const Pokemon(
    nama: 'Pikachu',
    tipe: 'Electric',
    gambar: 'pikachu.png',
    deskripsi: 'Pokemon tikus listrik yang sangat populer dan menjadi maskot seri Pokemon. Bisa mengeluarkan listrik bertegangan tinggi dari pipinya yang merah. Saat marah, listrik yang dikeluarkan bisa sangat berbahaya.',
    kemampuan: 'Static — lawan yang menyentuhnya bisa terkena kelumpuhan',
    evolusi: 'Pichu → Pikachu → Raichu',
    kelemahan: ['Ground'],
    hp: 35,
    attack: 55,
    defense: 40,
    speed: 90,
  ),
  const Pokemon(
    nama: 'Charizard',
    tipe: 'Fire',
    gambar: 'charizard.png',
    deskripsi: 'Pokemon naga api yang sangat kuat dan bertemperamen tinggi. Api dari mulutnya bisa mencairkan batu dan gletser. Tidak mau bertarung melawan lawan yang lebih lemah darinya.',
    kemampuan: 'Blaze — kekuatan api meningkat saat HP menipis',
    evolusi: 'Charmander → Charmeleon → Charizard',
    kelemahan: ['Water', 'Rock', 'Electric'],
    hp: 78,
    attack: 84,
    defense: 78,
    speed: 100,
  ),
  const Pokemon(
    nama: 'Bulbasaur',
    tipe: 'Grass',
    gambar: 'bulbasaur.png',
    deskripsi: 'Pokemon benih yang membawa tanaman di punggungnya sejak lahir. Biji tanaman itu menyerap sinar matahari dan tumbuh semakin besar seiring waktu. Sangat jinak dan mudah dirawat.',
    kemampuan: 'Overgrow — kekuatan Grass meningkat saat HP menipis',
    evolusi: 'Bulbasaur → Ivysaur → Venusaur',
    kelemahan: ['Fire', 'Ice', 'Flying', 'Psychic'],
    hp: 45,
    attack: 49,
    defense: 49,
    speed: 45,
  ),
  const Pokemon(
    nama: 'Blastoise',
    tipe: 'Water',
    gambar: 'blastoise.png',
    deskripsi: 'Pokemon kura-kura air dengan meriam di cangkangnya. Air bertekanan tinggi yang disemprotkan mampu menembus baja tebal. Cangkangnya sangat keras sehingga bisa menahan serangan apapun.',
    kemampuan: 'Torrent — kekuatan Water meningkat saat HP menipis',
    evolusi: 'Squirtle → Wartortle → Blastoise',
    kelemahan: ['Electric', 'Grass'],
    hp: 79,
    attack: 83,
    defense: 100,
    speed: 78,
  ),
  const Pokemon(
    nama: 'Gengar',
    tipe: 'Ghost',
    gambar: 'gengar.png',
    deskripsi: 'Pokemon hantu yang suka bersembunyi di bayangan dan tempat gelap. Senang menakut-nakuti orang dan menyerap panas tubuh korbannya. Kehadirannya membuat suhu ruangan turun drastis.',
    kemampuan: 'Cursed Body — serangan lawan bisa tiba-tiba tidak bisa digunakan',
    evolusi: 'Gastly → Haunter → Gengar',
    kelemahan: ['Ghost', 'Dark', 'Psychic'],
    hp: 60,
    attack: 65,
    defense: 60,
    speed: 110,
  ),
  const Pokemon(
    nama: 'Lucario',
    tipe: 'Fighting',
    gambar: 'lucario.png',
    deskripsi: 'Pokemon yang bisa merasakan dan mengeluarkan gelombang energi bernama aura. Dengan aura tersebut, ia bisa membaca pikiran dan perasaan makhluk lain. Sangat setia dan terikat kuat pada pemiliknya.',
    kemampuan: 'Steadfast — kecepatan meningkat setiap kali terkena serangan yang membuat gentar',
    evolusi: 'Riolu → Lucario',
    kelemahan: ['Fire', 'Flying', 'Psychic'],
    hp: 70,
    attack: 110,
    defense: 70,
    speed: 90,
  ),
  const Pokemon(
    nama: 'Gyarados',
    tipe: 'Water',
    gambar: 'gyarados.png',
    deskripsi: 'Pokemon ular laut yang sangat ganas dan sulit dikendalikan. Sekali mengamuk, bisa menghancurkan seluruh kota dalam semalam. Dipercaya bahwa amarahnya bisa berlangsung selama sebulan penuh.',
    kemampuan: 'Intimidate — menurunkan Attack lawan saat masuk pertarungan',
    evolusi: 'Magikarp → Gyarados',
    kelemahan: ['Electric', 'Rock'],
    hp: 95,
    attack: 125,
    defense: 79,
    speed: 81,
  ),
  const Pokemon(
    nama: 'Dragonite',
    tipe: 'Dragon',
    gambar: 'dragonite.png',
    deskripsi: 'Pokemon naga yang ramah dan sangat cerdas. Bisa terbang lebih cepat dari pesawat dan mengelilingi bumi hanya dalam 16 jam. Dikenal suka membantu manusia yang tersesat di lautan.',
    kemampuan: 'Multiscale — damage berkurang saat HP penuh',
    evolusi: 'Dratini → Dragonair → Dragonite',
    kelemahan: ['Ice', 'Dragon', 'Fairy'],
    hp: 91,
    attack: 134,
    defense: 95,
    speed: 80,
  ),
  const Pokemon(
    nama: 'Snorlax',
    tipe: 'Normal',
    gambar: 'snorlax.png',
    deskripsi: 'Pokemon raksasa yang kegiatannya hanya makan dan tidur. Bisa menghabiskan 400 kg makanan sehari sebelum tidur kembali. Tubuhnya yang besar sering menghalangi jalan dan hanya bisa dibangunkan dengan Pokeflute.',
    kemampuan: 'Thick Fat — tahan terhadap serangan Fire dan Ice',
    evolusi: 'Munchlax → Snorlax',
    kelemahan: ['Fighting'],
    hp: 160,
    attack: 110,
    defense: 65,
    speed: 30,
  ),
  const Pokemon(
    nama: 'Alakazam',
    tipe: 'Psychic',
    gambar: 'alakazam.png',
    deskripsi: 'Pokemon dengan IQ luar biasa yang diklaim mencapai 5000. Otaknya terus berkembang sepanjang hidup. Selalu memegang dua sendok yang diperkuat dengan kekuatan psikisnya dan bisa menekuk sendok itu hanya dengan pikiran.',
    kemampuan: 'Magic Guard — hanya bisa terluka oleh serangan langsung',
    evolusi: 'Abra → Kadabra → Alakazam',
    kelemahan: ['Bug', 'Ghost', 'Dark'],
    hp: 55,
    attack: 50,
    defense: 45,
    speed: 120,
  ),
  const Pokemon(
    nama: 'Machamp',
    tipe: 'Fighting',
    gambar: 'machamp.png',
    deskripsi: 'Pokemon dengan empat lengan yang sangat kuat. Bisa memukul hingga 1000 kali hanya dalam 2 detik. Keempat tangannya bisa bergerak secara bersamaan dan independen, membuatnya menjadi petarung yang luar biasa.',
    kemampuan: 'Guts — Attack meningkat saat terkena status efek',
    evolusi: 'Machop → Machoke → Machamp',
    kelemahan: ['Flying', 'Psychic', 'Fairy'],
    hp: 90,
    attack: 130,
    defense: 80,
    speed: 55,
  ),
  const Pokemon(
    nama: 'Eevee',
    tipe: 'Normal',
    gambar: 'eevee.png',
    deskripsi: 'Pokemon unik yang memiliki struktur genetik sangat tidak stabil sehingga bisa berevolusi menjadi banyak bentuk berbeda. Bentuk evolusinya tergantung pada batu evolusi, lokasi, atau hubungan dengan pemiliknya.',
    kemampuan: 'Adaptability — bonus STAB meningkat dari 1.5x menjadi 2x',
    evolusi: 'Eevee → Vaporeon / Jolteon / Flareon / Espeon / Umbreon / Leafeon / Glaceon / Sylveon',
    kelemahan: ['Fighting'],
    hp: 55,
    attack: 55,
    defense: 50,
    speed: 55,
  ),
  const Pokemon(
    nama: 'Vaporeon',
    tipe: 'Water',
    gambar: 'vaporeon.png',
    deskripsi: 'Evolusi air dari Eevee menggunakan Water Stone. Molekul tubuhnya mirip dengan air sehingga bisa melebur dan menghilang di dalam air. Sering ditemukan di tepi danau dan sungai yang jernih.',
    kemampuan: 'Water Absorb — menyerap serangan Water untuk memulihkan HP',
    evolusi: 'Eevee → Vaporeon (gunakan Water Stone)',
    kelemahan: ['Electric', 'Grass'],
    hp: 130,
    attack: 65,
    defense: 60,
    speed: 65,
  ),
  const Pokemon(
    nama: 'Jolteon',
    tipe: 'Electric',
    gambar: 'jolteon.png',
    deskripsi: 'Evolusi listrik dari Eevee menggunakan Thunder Stone. Bulunya yang tajam seperti jarum bisa berdiri tegak dan melepaskan listrik hingga 10.000 volt. Sangat cepat dan lincah dalam pertarungan.',
    kemampuan: 'Volt Absorb — menyerap serangan Electric untuk memulihkan HP',
    evolusi: 'Eevee → Jolteon (gunakan Thunder Stone)',
    kelemahan: ['Ground'],
    hp: 65,
    attack: 65,
    defense: 60,
    speed: 130,
  ),
  const Pokemon(
    nama: 'Flareon',
    tipe: 'Fire',
    gambar: 'flareon.png',
    deskripsi: 'Evolusi api dari Eevee menggunakan Fire Stone. Memiliki kantong udara khusus di dalam tubuh yang berfungsi seperti tungku pembakaran. Suhu tubuhnya bisa mencapai 1650 derajat Celsius saat menghembuskan api.',
    kemampuan: 'Flash Fire — kebal terhadap serangan Fire dan memperkuatnya',
    evolusi: 'Eevee → Flareon (gunakan Fire Stone)',
    kelemahan: ['Water', 'Ground', 'Rock'],
    hp: 65,
    attack: 130,
    defense: 60,
    speed: 65,
  ),
  const Pokemon(
    nama: 'Greninja',
    tipe: 'Water',
    gambar: 'greninja.png',
    deskripsi: 'Pokemon ninja katak yang bergerak dengan kecepatan luar biasa sehingga hampir tidak terlihat. Bisa membuat shuriken dari air bertekanan tinggi yang tajamnya setara pisau. Lidahnya yang panjang digunakan untuk melilitkan diri saat beraksi.',
    kemampuan: 'Protean — tipe berubah sesuai gerakan yang digunakan',
    evolusi: 'Froakie → Frogadier → Greninja',
    kelemahan: ['Electric', 'Grass'],
    hp: 72,
    attack: 95,
    defense: 67,
    speed: 122,
  ),
  const Pokemon(
    nama: 'Tyranitar',
    tipe: 'Rock',
    gambar: 'tyranitar.png',
    deskripsi: 'Pokemon batu raksasa dengan kekuatan yang bisa meratakan gunung dan mengubur kota dalam sekejap. Sangat keras kepala dan suka bertarung. Kehadirannya secara alami menciptakan badai pasir di sekitarnya.',
    kemampuan: 'Sand Stream — otomatis menciptakan badai pasir saat masuk pertarungan',
    evolusi: 'Larvitar → Pupitar → Tyranitar',
    kelemahan: ['Fighting', 'Ground', 'Bug', 'Steel', 'Water', 'Grass'],
    hp: 100,
    attack: 134,
    defense: 110,
    speed: 61,
  ),
];
